GitActions-Teste de imagem

diff --git a/.github/workflows/cicd-app.yml b/.github/workflows/cicd-app.yml
--- a/.github/workflows/cicd-app.yml
+++ b/.github/workflows/cicd-app.yml
@@ -26,9 +26,26 @@ jobs:
       - uses: actions/checkout@v3
 
       # Runs a set of commands using the runners shell
-      - name: Build APP Image
+      - name: Build PRODUCTION APP Image
         run: |
           docker login -u qsquad3 -p ${{ secrets.TOKEN_DKR_HUB }}
           docker build -t app .
           docker tag app qsquad3/app
           docker push qsquad3/app
+      - name: Build TEST Image
+        run: |
+          sed -i 's/10.0.3.14/pgsql/' Dockerfile
+          docker build . -t app-quode
+          docker-compose -f pgsql-to-cicd.yml up -d
+      - name: HealCheck TEST Image
+        run: |
+          if [ "`curl -s http://localhost:8500/healthcheck|awk {'print$3'}`" = "OK" ]
+              then
+                  echo "TESTE [ OK ]"
+                  exit 0
+          else
+                  echo "ERROR [ ERROR ]"
+                  exit 1
+          fi
+
+          
