GitActions-Teste de imagem

diff --git a/.github/workflows/cicd-app.yml b/.github/workflows/cicd-app.yml
--- a/.github/workflows/cicd-app.yml
+++ b/.github/workflows/cicd-app.yml
@@ -48,14 +48,17 @@ jobs:
     steps:
       - uses: actions/checkout@v3  
       - name: HealthCheck TEST Image
+        #run: |
+        #  if [ "`curl -s http://localhost:8500/healthcheck|awk {'print$3'}`" = "OK" ]
+        #      then
+        #          echo "TESTE [ OK ]"
+        #          exit 0
+        #  else
+        #          echo "ERROR [ ERROR ]"
+        #          exit 1
+        #  fi
         run: |
-          if [ "`curl -s http://localhost:8500/healthcheck|awk {'print$3'}`" = "OK" ]
-              then
-                  echo "TESTE [ OK ]"
-                  exit 0
-          else
-                  echo "ERROR [ ERROR ]"
-                  exit 1
-          fi
+        ls
+        curl http://localhost:8500/healthcheck
 
           
